name: Update

on: push

env:
  COMMIT_SHA: "${{ github.sha }}"
  GIT_REF: "${{ github.ref }}"
  LOG_LEVEL: "WARN"
  S3_BUCKET_NAME: "qinab.com"

jobs:
  deploy:
    name: "Sync to S3 bucket"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Render HTML email templates
        run: aws s3 sync . s3://$S3_BUCKET_NAME/ --delete --acl public-read

      - name: Render HTML email templates
        run: aws s3 sync . s3://www.$S3_BUCKET_NAME/ --delete --acl public-read
